In [1]:
import os
import torch
import torchvision
from PIL import Image
import matplotlib.pyplot as plt
import torchvision.transforms as transforms  
from torch.utils.data import Dataset, DataLoader
import cv2
import numpy as np

In [2]:
class ImageDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = root_dir
        self.transform = transform
        self.image_paths = [os.path.join(root_dir, f) for f in os.listdir(root_dir) if f.endswith(('jpg', 'png', 'jpeg'))]

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = Image.fromarray(image)
        
        if self.transform:
            image = self.transform(image)
        
        return image

transforms_image = transforms.Compose([
    transforms.Resize((512, 512)),
    transforms.ToTensor()
])

dataset = ImageDataset(root_dir='/kaggle/input/cat-and-dog/training_set/training_set/cats', transform=transforms_image)
image_loader = DataLoader(dataset, batch_size=32, shuffle=True)


In [3]:
for image in image_loader:
    print(image.size(1))
    ans = image.view(32, 3, -1)
    print(image.view(32, 3, -1).shape)
    print(ans.mean(2))
    print(ans.mean(2).sum(0))
    break

3
torch.Size([32, 3, 262144])
tensor([[0.4889, 0.5552, 0.5440],
        [0.4869, 0.4460, 0.4274],
        [0.4495, 0.4003, 0.4088],
        [0.4776, 0.4253, 0.3514],
        [0.4444, 0.4780, 0.4243],
        [0.4423, 0.2993, 0.2645],
        [0.3838, 0.3921, 0.3441],
        [0.4809, 0.4509, 0.4173],
        [0.7854, 0.6937, 0.6601],
        [0.4459, 0.4006, 0.3941],
        [0.5154, 0.4722, 0.5369],
        [0.4603, 0.4199, 0.4028],
        [0.3575, 0.2332, 0.1805],
        [0.2941, 0.2951, 0.2929],
        [0.6550, 0.3173, 0.3280],
        [0.5531, 0.5141, 0.5077],
        [0.4608, 0.4569, 0.4800],
        [0.5984, 0.4526, 0.3301],
        [0.6656, 0.5672, 0.4327],
        [0.7304, 0.6750, 0.6563],
        [0.6571, 0.5262, 0.4322],
        [0.4344, 0.4262, 0.4180],
        [0.4195, 0.3583, 0.3384],
        [0.5881, 0.5535, 0.4739],
        [0.5208, 0.4615, 0.4015],
        [0.6367, 0.6081, 0.5847],
        [0.2648, 0.2471, 0.2342],
        [0.4437, 0.3740, 0.3260],
        [0.4132, 0

In [4]:
def get_mean_std(loader):
    mean = 0.
    std = 0.
    total_image_count = 0
    for image in loader:
        imageCount_batch = image.size(0)
        image = image.view(imageCount_batch, image.size(1), -1)
        mean += image.mean(2).sum(0)

        std += image.std(2).sum(0)
        total_image_count += imageCount_batch
    
    mean /= total_image_count
    std /= total_image_count

    return mean, std

In [5]:
get_mean_std(image_loader)

(tensor([0.4847, 0.4487, 0.4169]), tensor([0.2300, 0.2272, 0.2283]))

## Try Another Dataset for Validation

In [6]:
N_dataset = ImageDataset(root_dir=r'/kaggle/input/cat-and-dog/training_set/training_set/dogs', transform=transforms_image)
Image_loader = DataLoader(N_dataset, batch_size=32, shuffle=True)

In [7]:
get_mean_std(Image_loader)

(tensor([0.4919, 0.4615, 0.4179]), tensor([0.2256, 0.2184, 0.2183]))